apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T14:11:14Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2075"
  uid: c3b345ea-92dd-443a-8435-44fc6db7e66b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.3.51
  clusterIPs:
  - 10.104.3.51
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30976
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
